#Copyright (c) 2020, Oracle and/or its affiliates.
#The Universal Permissive License (UPL), Version 1.0
#

# Convert to CDB in target OCI DBSystem
- name: Convert to CDB in target OCI DBSystem
  hosts: target[0]
  roles:
    - target_plug_noncdb_to_cdb_role
